const sharedContact = {
  email: "wangxiwei2002@gmail.com",
  emailHref: "mailto:wangxiwei2002@gmail.com",
  phone: "+1 (437) 872-3279",
  phoneHref: "tel:+14378723279",
  website: "wxw2002a.github.io",
  websiteHref: "https://wxw2002a.github.io/",
  github: "@wxw2002a",
  githubHref: "https://github.com/wxw2002a",
  resumeHref: "Xiwei-Wang-Resume.pdf",
};

export const supportedLocales = ["en", "zh"];
export const defaultLocale = "en";

export const content = {
  en: {
    locale: "en",
    localeName: "English",
    meta: {
      title: "Xiwei Wang — Full-Stack & AI Product Engineer",
      description:
        "Xiwei Wang builds full-stack products, AI platforms, mobile applications, backend services, and real-time computer-vision systems.",
    },
    ui: {
      skipToContent: "Skip to main content",
      brandRole: "Engineer / Builder",
      nav: [
        { id: "profile", href: "#profile", label: "Profile" },
        { id: "experience", href: "#experience", label: "Experience" },
        { id: "work", href: "#work", label: "Selected work" },
        { id: "background", href: "#background", label: "Background" },
        { id: "contact", href: "#contact", label: "Contact" },
      ],
      controls: {
        openMenu: "Open menu",
        closeMenu: "Close menu",
        switchLanguage: "切换至中文",
        switchTheme: "Switch color theme",
        lightTheme: "Use light theme",
        darkTheme: "Use dark theme",
      },
      actions: {
        explore: "Explore my work",
        downloadResume: "Download résumé",
        viewResume: "View full résumé",
        viewDetails: "View role details",
        hideDetails: "Hide role details",
        startConversation: "Start a conversation",
        backToTop: "Back to top",
        scroll: "Scroll to explore",
      },
      projectFilters: [
        { id: "all", label: "All" },
        { id: "systems", label: "Systems" },
        { id: "ai", label: "AI / ML" },
        { id: "gpu", label: "GPU" },
      ],
      sectionLabels: {
        profile: "01 / PROFILE",
        experience: "02 / EXPERIENCE",
        work: "03 / SELECTED WORK",
        background: "04 / BACKGROUND",
        contact: "05 / CONTACT",
      },
      labels: {
        selectedImpact: "Selected impact",
        education: "Education",
        technicalToolkit: "Technical toolkit",
        spokenLanguages: "Spoken languages",
        email: "Email",
        phone: "Phone",
        website: "Website",
        github: "GitHub",
        resume: "Résumé",
      },
      footerNote: "Designed and engineered with intention.",
    },
    hero: {
      eyebrow: "FULL-STACK / AI PRODUCT / REAL-TIME SYSTEMS",
      name: "XIWEI WANG",
      headlineLead: "I build products",
      headlineAccent: "that ship.",
      headline: "From product intent to production systems.",
      lede:
        "Across mobile, web, backend, AI, cloud, and performance-sensitive computer vision, I connect technical direction with hands-on delivery.",
      study:
        "MEng in Electrical & Computer Engineering (Software Engineering) · University of Waterloo · 2025—2026",
    },
    impact: [
      {
        id: "workstreams",
        value: "6",
        label: "cross-functional workstreams",
        detail: "Led across frontend, backend, AI/ML, design, and product",
      },
      {
        id: "response-time",
        value: "−25%",
        label: "average response time",
        detail: "Through API and database optimization",
      },
      {
        id: "vision-throughput",
        value: "600",
        label: "images per second",
        detail: "Processed from live camera feeds in C++ / Qt",
      },
    ],
    capabilities: {
      title: "Product thinking. Engineering depth.",
      intro:
        "I am an Electrical and Computer Engineering MEng candidate at the University of Waterloo. My work spans product planning, cross-platform applications, backend services, AI pipelines, cloud deployment, and real-time industrial software.",
      items: [
        {
          id: "product-delivery",
          index: "01",
          title: "Product delivery",
          text:
            "Translate product requirements into technical priorities, coordinate milestones, resolve cross-team blockers, and carry releases through integration.",
          tags: ["Planning", "Coordination", "Delivery"],
        },
        {
          id: "full-stack-products",
          index: "02",
          title: "Full-stack products",
          text:
            "Build mobile and web experiences with React, React Native, and Flutter, backed by Java/Spring Boot, Node.js/Express, Django, and structured data systems.",
          tags: ["Web", "Mobile", "Backend"],
        },
        {
          id: "ai-real-time",
          index: "03",
          title: "AI & real-time systems",
          text:
            "Connect LLM and image-generation services in the cloud, and engineer performance-sensitive C++/Qt computer-vision applications on Linux.",
          tags: ["AI", "Cloud", "Computer vision"],
        },
      ],
    },
    experienceIntro: {
      title: "From product direction to production delivery.",
      text:
        "Five roles across AI products, mobile platforms, backend systems, and industrial automation.",
    },
    experiences: [
      {
        id: "ipmd",
        company: "IPMD, Inc.",
        role: "Technical Manager Intern",
        start: "2026-05",
        end: "2026-08",
        period: "May 2026 — Aug 2026",
        location: "California, United States · Remote",
        highlight: { value: "35%", label: "faster MVP delivery" },
        metrics: [
          { value: "70+", label: "image-card assets" },
          { value: "5", label: "product categories" },
          { value: "40%", label: "better prompt consistency" },
          { value: "50%", label: "less manual configuration time" },
          { value: "30%", label: "shorter iteration cycles" },
          { value: "6", label: "cross-functional workstreams" },
          { value: "35%", label: "faster MVP delivery" },
        ],
        bullets: [
          "Built and deployed an end-to-end AI image-generation platform using React, TypeScript, Node.js/Express, Qwen/Gemini, Stable Diffusion 1.5, Docker, and Microsoft Azure, supporting card selections, text input, image uploads, prompt generation, and artwork generation.",
          "Standardized prompt-generation workflows and 70+ image-card assets across 5 product categories, improving prompt consistency by 40%, reducing manual configuration time by 50%, and shortening iteration cycles by 30%.",
          "Led 6 cross-functional workstreams across frontend, backend, AI/ML, design, and product, translating product requirements into technical priorities, coordinating development milestones, resolving cross-team blockers, and accelerating MVP delivery by 35%.",
        ],
        tech: [
          "React",
          "TypeScript",
          "Node.js / Express",
          "Qwen / Gemini",
          "Stable Diffusion 1.5",
          "Docker",
          "Microsoft Azure",
        ],
      },
      {
        id: "folobotics",
        company: "FoloBotics",
        role: "Full-Stack Developer Intern",
        start: "2026-01",
        end: "2026-04",
        period: "Jan 2026 — Apr 2026",
        location: "Ontario, Canada",
        highlight: { value: "−25%", label: "average response time" },
        metrics: [{ value: "25%", label: "lower average response time" }],
        bullets: [
          "Developed Java/Spring Boot backend services and REST APIs for user, task, recommendation, and warehouse workflows consumed by Flutter clients.",
          "Designed PostgreSQL, MySQL, and Redis data flows and optimized API/database interactions, reducing average response time by 25% and improving backend performance.",
        ],
        tech: [
          "Java",
          "Spring Boot",
          "REST APIs",
          "Flutter",
          "PostgreSQL",
          "MySQL",
          "Redis",
        ],
      },
      {
        id: "selest-security",
        company: "SELEST Security",
        role: "Full-Stack Developer",
        start: "2025-09",
        end: "2025-12",
        period: "Sep 2025 — Dec 2025",
        location: "Ontario, Canada",
        highlight: { value: "5+", label: "booking and shift workflows" },
        metrics: [{ value: "5+", label: "booking and shift-management workflows" }],
        bullets: [
          "Built and shipped a multi-role React Native application using TypeScript and JavaScript, Node.js/Express, MongoDB, and Google Cloud, supporting production releases to the App Store and Google Play.",
          "Implemented 5+ booking and shift-management workflows through REST API integration, translating operational requirements into reliable end-to-end product functionality.",
        ],
        tech: [
          "React Native",
          "TypeScript",
          "JavaScript",
          "Node.js / Express",
          "MongoDB",
          "Google Cloud",
          "REST APIs",
        ],
      },
      {
        id: "hit-robotics",
        company: "Harbin Institute of Technology Robot Technology Research Institute",
        role: "Industrial Vision Platform Development Intern",
        start: "2025-06",
        end: "2025-08",
        period: "Jun 2025 — Aug 2025",
        location: "China",
        highlight: { value: "600", label: "images per second" },
        metrics: [{ value: "600", label: "images processed per second" }],
        bullets: [
          "Built a real-time C++/Qt computer-vision application on Linux that processed up to 600 images per second from live camera feeds, debugging performance-sensitive components and integrating application modules.",
          "Developed a Python/Django REST backend for detection logging, parameter synchronization, and offline frame analysis, connecting vision outputs to structured application services.",
        ],
        tech: ["C++", "Qt", "Linux", "Python", "Django", "REST APIs"],
      },
      {
        id: "sinopec",
        company: "Sinopec Group",
        role: "Application Intern at the Information Center",
        start: "2024-07",
        end: "2024-08",
        period: "Jul 2024 — Aug 2024",
        location: "China",
        highlight: { value: "RCS", label: "warehouse automation" },
        metrics: [],
        bullets: [
          "Implemented QR/2D-code recognition in Python with Pyzbar and integrated recognition results with backend services for reliable unmanned-warehouse operations.",
          "Integrated and tested software components for an unmanned warehouse digital storage system and Robot Control System (RCS), supporting application and automation workflows.",
        ],
        tech: ["Python", "Pyzbar", "RCS", "Backend services"],
      },
    ],
    projectsIntro: {
      title: "Engineering beyond the happy path.",
      text:
        "Selected systems, GPU, and applied AI work preserved from my engineering portfolio.",
    },
    projects: [
      {
        id: "java-tcp-server",
        index: "01",
        category: "systems",
        categoryLabel: "SYSTEMS",
        title: "High-Performance Java Server",
        metric: "120 → ~40 ms",
        description:
          "A multithreaded Java TCP server on Ubuntu with socket-level tuning, reducing latency from 120 ms to approximately 40 ms.",
        tech: ["Java", "TCP", "Ubuntu", "Performance"],
      },
      {
        id: "cuda-convolution",
        index: "02",
        category: "gpu",
        categoryLabel: "GPU",
        title: "CUDA Convolution Acceleration",
        metric: "CUDA 12.4 · RTX 3070",
        description:
          "Implemented 2D convolution CUDA kernels on an RTX 3070 and built Python benchmarks for performance evaluation.",
        tech: ["CUDA 12.4", "C / C++", "Python", "RTX 3070"],
      },
      {
        id: "audio-anomaly-detection",
        index: "03",
        category: "ai",
        categoryLabel: "AI / ML",
        title: "Audio Anomaly Detection",
        metric: "YAMNet",
        description:
          "YAMNet-based classification with thresholding designed to reduce false positives in industrial environments.",
        tech: ["Python", "TensorFlow", "YAMNet", "Audio ML"],
      },
      {
        id: "template-roi-toolkit",
        index: "04",
        category: "systems",
        categoryLabel: "VISION UI",
        title: "Template / ROI Toolkit",
        metric: "Template / ROI",
        description:
          "Proportional template fitting and ROI parameter controls for distortion-free industrial inspection interfaces.",
        tech: ["C / C++", "Qt", "Computer Vision", "UI Systems"],
      },
    ],
    backgroundIntro: {
      title: "Education meets engineering practice.",
      text:
        "Graduate software engineering study backed by an electronic-systems foundation and a practical full-stack toolkit.",
    },
    education: [
      {
        id: "waterloo",
        school: "University of Waterloo",
        start: "2025-09",
        end: "2026-12",
        period: "Sep 2025 — Dec 2026",
        degree: "Master of Engineering in Electrical and Computer Engineering",
        detail: "Software Engineering",
      },
      {
        id: "yanshan",
        school: "Yanshan University",
        start: "2021-09",
        end: "2025-06",
        period: "Sep 2021 — Jun 2025",
        degree: "Bachelor of Electronic Science and Technology",
        detail: "GPA: 86 / 100",
      },
    ],
    skills: [
      {
        id: "languages",
        label: "Languages",
        items: ["Java", "TypeScript", "JavaScript", "Python", "C / C++", "SQL"],
      },
      {
        id: "frontend-mobile",
        label: "Frontend & Mobile",
        items: ["React", "React Native", "Flutter"],
      },
      {
        id: "backend-cloud",
        label: "Backend & Cloud",
        items: [
          "Spring Boot",
          "Node.js / Express",
          "Django",
          "REST APIs",
          "Microsoft Azure",
          "Google Cloud",
          "Docker",
        ],
      },
      {
        id: "data-ai",
        label: "Data & AI",
        items: [
          "PostgreSQL",
          "MySQL",
          "MongoDB",
          "Redis",
          "Qwen / Gemini",
          "Stable Diffusion 1.5",
        ],
      },
      {
        id: "project-toolkit",
        label: "Additional project tools",
        items: ["Kotlin", "HTML / CSS", "Git", "Linux", "Bash", "Qt", "CUDA", "TensorFlow / YAMNet"],
      },
    ],
    spokenLanguages: [
      { id: "english", language: "English", level: "Fluent" },
      { id: "chinese", language: "Chinese", level: "Native" },
      { id: "french", language: "French", level: "Basic" },
    ],
    contact: {
      ...sharedContact,
      title: "Let’s build something that holds up.",
      intro:
        "For full-stack, AI-enabled product, or systems work, email is the fastest way to reach me.",
      links: [
        {
          id: "email",
          label: "Email",
          value: sharedContact.email,
          href: sharedContact.emailHref,
        },
        {
          id: "phone",
          label: "Phone",
          value: sharedContact.phone,
          href: sharedContact.phoneHref,
        },
        {
          id: "website",
          label: "Website",
          value: sharedContact.website,
          href: sharedContact.websiteHref,
          external: true,
        },
        {
          id: "github",
          label: "GitHub",
          value: sharedContact.github,
          href: sharedContact.githubHref,
          external: true,
        },
        {
          id: "resume",
          label: "Résumé",
          value: "View PDF",
          href: sharedContact.resumeHref,
          external: true,
        },
      ],
    },
  },

  zh: {
    locale: "zh-CN",
    localeName: "中文",
    meta: {
      title: "王曦威 — 全栈与 AI 产品工程师",
      description:
        "王曦威专注于全栈产品、AI 平台、移动应用、后端服务与实时计算机视觉系统。",
    },
    ui: {
      skipToContent: "跳到主要内容",
      brandRole: "工程师 / 创造者",
      nav: [
        { id: "profile", href: "#profile", label: "简介" },
        { id: "experience", href: "#experience", label: "经历" },
        { id: "work", href: "#work", label: "项目" },
        { id: "background", href: "#background", label: "背景" },
        { id: "contact", href: "#contact", label: "联系" },
      ],
      controls: {
        openMenu: "打开菜单",
        closeMenu: "关闭菜单",
        switchLanguage: "Switch to English",
        switchTheme: "切换配色主题",
        lightTheme: "使用浅色主题",
        darkTheme: "使用深色主题",
      },
      actions: {
        explore: "查看我的经历",
        downloadResume: "下载简历",
        viewResume: "查看完整简历",
        viewDetails: "查看职位详情",
        hideDetails: "收起职位详情",
        startConversation: "发起联系",
        backToTop: "返回顶部",
        scroll: "向下探索",
      },
      projectFilters: [
        { id: "all", label: "全部" },
        { id: "systems", label: "系统" },
        { id: "ai", label: "AI / 机器学习" },
        { id: "gpu", label: "GPU" },
      ],
      sectionLabels: {
        profile: "01 / 简介",
        experience: "02 / 经历",
        work: "03 / 精选项目",
        background: "04 / 背景",
        contact: "05 / 联系",
      },
      labels: {
        selectedImpact: "代表性成果",
        education: "教育经历",
        technicalToolkit: "技术栈",
        spokenLanguages: "语言能力",
        email: "邮箱",
        phone: "电话",
        website: "网站",
        github: "GitHub",
        resume: "简历",
      },
      footerNote: "用心设计，也用心实现。",
    },
    hero: {
      eyebrow: "全栈 / AI 产品 / 实时系统",
      name: "XIWEI WANG",
      headlineLead: "我把产品构想",
      headlineAccent: "变成生产系统。",
      headline: "从产品构想到生产系统。",
      lede:
        "横跨移动端、Web、后端、AI、云服务与高性能计算机视觉，我把技术方向转化为真正交付的产品。",
      study:
        "滑铁卢大学 · 电气与计算机工程硕士（软件工程方向）· 2025—2026",
    },
    impact: [
      {
        id: "workstreams",
        value: "6",
        label: "个跨职能工作流",
        detail: "覆盖前端、后端、AI/ML、设计与产品",
      },
      {
        id: "response-time",
        value: "−25%",
        label: "平均响应时间",
        detail: "通过 API 与数据库交互优化实现",
      },
      {
        id: "vision-throughput",
        value: "600",
        label: "张图像 / 秒",
        detail: "以 C++ / Qt 实时处理相机画面",
      },
    ],
    capabilities: {
      title: "产品思维，工程深度。",
      intro:
        "我正在滑铁卢大学攻读电气与计算机工程硕士。我的工作覆盖产品规划、跨平台应用、后端服务、AI 流程、云端部署与工业实时软件。",
      items: [
        {
          id: "product-delivery",
          index: "01",
          title: "产品交付",
          text:
            "将产品需求转化为技术优先级，协调开发里程碑、解决跨团队阻塞，并推动版本完成集成。",
          tags: ["规划", "协作", "交付"],
        },
        {
          id: "full-stack-products",
          index: "02",
          title: "全栈产品",
          text:
            "使用 React、React Native 与 Flutter 构建 Web 和移动端体验，并以 Java/Spring Boot、Node.js/Express、Django 与结构化数据系统提供后端支持。",
          tags: ["Web", "移动端", "后端"],
        },
        {
          id: "ai-real-time",
          index: "03",
          title: "AI 与实时系统",
          text:
            "在云端连接大语言模型与图像生成服务，并在 Linux 上开发对性能敏感的 C++/Qt 计算机视觉应用。",
          tags: ["AI", "云服务", "计算机视觉"],
        },
      ],
    },
    experienceIntro: {
      title: "从产品方向到生产交付。",
      text: "五段经历，覆盖 AI 产品、移动平台、后端系统与工业自动化。",
    },
    experiences: [
      {
        id: "ipmd",
        company: "IPMD, Inc.",
        role: "技术经理实习生",
        start: "2026-05",
        end: "2026-08",
        period: "2026年5月—8月",
        location: "美国加利福尼亚州 · 远程",
        highlight: { value: "35%", label: "MVP 交付提速" },
        metrics: [
          { value: "70+", label: "个图像卡片素材" },
          { value: "5", label: "个产品类别" },
          { value: "40%", label: "提示词一致性提升" },
          { value: "50%", label: "手动配置时间减少" },
          { value: "30%", label: "迭代周期缩短" },
          { value: "6", label: "个跨职能工作流" },
          { value: "35%", label: "MVP 交付提速" },
        ],
        bullets: [
          "使用 React、TypeScript、Node.js/Express、Qwen/Gemini、Stable Diffusion 1.5、Docker 与 Microsoft Azure 构建并部署端到端 AI 图像生成平台，支持卡片选择、文本输入、图像上传、提示词生成与艺术作品生成。",
          "标准化提示词生成流程，并整理覆盖 5 个产品类别的 70+ 个图像卡片素材，使提示词一致性提升 40%、手动配置时间减少 50%、迭代周期缩短 30%。",
          "带领覆盖前端、后端、AI/ML、设计与产品的 6 个跨职能工作流，将产品需求转化为技术优先级，协调开发里程碑、解决跨团队阻塞，使 MVP 交付提速 35%。",
        ],
        tech: [
          "React",
          "TypeScript",
          "Node.js / Express",
          "Qwen / Gemini",
          "Stable Diffusion 1.5",
          "Docker",
          "Microsoft Azure",
        ],
      },
      {
        id: "folobotics",
        company: "FoloBotics",
        role: "全栈开发实习生",
        start: "2026-01",
        end: "2026-04",
        period: "2026年1月—4月",
        location: "加拿大安大略省",
        highlight: { value: "−25%", label: "平均响应时间" },
        metrics: [{ value: "25%", label: "平均响应时间降低" }],
        bullets: [
          "开发 Java/Spring Boot 后端服务与 REST API，为 Flutter 客户端的用户、任务、推荐与仓库工作流提供支持。",
          "设计 PostgreSQL、MySQL 与 Redis 数据流，并优化 API/数据库交互，使平均响应时间降低 25%，提升后端性能。",
        ],
        tech: [
          "Java",
          "Spring Boot",
          "REST APIs",
          "Flutter",
          "PostgreSQL",
          "MySQL",
          "Redis",
        ],
      },
      {
        id: "selest-security",
        company: "SELEST Security",
        role: "全栈开发工程师",
        start: "2025-09",
        end: "2025-12",
        period: "2025年9月—12月",
        location: "加拿大安大略省",
        highlight: { value: "5+", label: "个预约与排班工作流" },
        metrics: [{ value: "5+", label: "个预约与排班管理工作流" }],
        bullets: [
          "使用 React Native、TypeScript、JavaScript、Node.js/Express、MongoDB 与 Google Cloud 构建并发布多角色应用，支持 App Store 与 Google Play 的生产版本发布。",
          "通过 REST API 集成实现 5+ 个预约与排班管理工作流，将运营需求转化为可靠的端到端产品功能。",
        ],
        tech: [
          "React Native",
          "TypeScript",
          "JavaScript",
          "Node.js / Express",
          "MongoDB",
          "Google Cloud",
          "REST APIs",
        ],
      },
      {
        id: "hit-robotics",
        company: "哈尔滨工业大学机器人技术研究所",
        role: "工业视觉平台开发实习生",
        start: "2025-06",
        end: "2025-08",
        period: "2025年6月—8月",
        location: "中国",
        highlight: { value: "600", label: "张图像 / 秒" },
        metrics: [{ value: "600", label: "每秒处理图像数" }],
        bullets: [
          "在 Linux 上构建实时 C++/Qt 计算机视觉应用，可从相机实时画面中每秒处理多达 600 张图像，并调试性能敏感组件、集成应用模块。",
          "开发 Python/Django REST 后端，用于检测日志、参数同步与离线帧分析，将视觉输出连接至结构化应用服务。",
        ],
        tech: ["C++", "Qt", "Linux", "Python", "Django", "REST APIs"],
      },
      {
        id: "sinopec",
        company: "中国石化集团",
        role: "信息中心应用实习生",
        start: "2024-07",
        end: "2024-08",
        period: "2024年7月—8月",
        location: "中国",
        highlight: { value: "RCS", label: "仓储自动化" },
        metrics: [],
        bullets: [
          "使用 Python 与 Pyzbar 实现 QR/二维条码识别，并将识别结果接入后端服务，以支持可靠的无人仓库运行。",
          "集成并测试无人仓库数字存储系统与机器人控制系统（RCS）的软件组件，为应用及自动化工作流提供支持。",
        ],
        tech: ["Python", "Pyzbar", "RCS", "后端服务"],
      },
    ],
    projectsIntro: {
      title: "面向真实约束的工程实践。",
      text: "保留自原工程作品集的系统、GPU 与应用 AI 精选项目。",
    },
    projects: [
      {
        id: "java-tcp-server",
        index: "01",
        category: "systems",
        categoryLabel: "系统",
        title: "高性能 Java 服务器",
        metric: "120 → ~40 ms",
        description:
          "在 Ubuntu 上构建多线程 Java TCP 服务器，通过套接字层调优将延迟从 120 ms 降至约 40 ms。",
        tech: ["Java", "TCP", "Ubuntu", "性能优化"],
      },
      {
        id: "cuda-convolution",
        index: "02",
        category: "gpu",
        categoryLabel: "GPU",
        title: "CUDA 卷积加速",
        metric: "CUDA 12.4 · RTX 3070",
        description:
          "在 RTX 3070 上实现二维卷积 CUDA 内核，并编写 Python 基准测试进行性能评估。",
        tech: ["CUDA 12.4", "C / C++", "Python", "RTX 3070"],
      },
      {
        id: "audio-anomaly-detection",
        index: "03",
        category: "ai",
        categoryLabel: "AI / 机器学习",
        title: "音频异常检测",
        metric: "YAMNet",
        description:
          "基于 YAMNet 的分类方案，结合阈值机制，以减少工业环境中的误报。",
        tech: ["Python", "TensorFlow", "YAMNet", "音频机器学习"],
      },
      {
        id: "template-roi-toolkit",
        index: "04",
        category: "systems",
        categoryLabel: "视觉界面",
        title: "Template / ROI 工具集",
        metric: "Template / ROI",
        description:
          "为工业检测界面实现按比例模板适配与 ROI 参数控制，避免画面变形。",
        tech: ["C / C++", "Qt", "计算机视觉", "界面系统"],
      },
    ],
    backgroundIntro: {
      title: "教育背景与工程实践并行。",
      text: "软件工程研究生学习，以电子系统基础与实用全栈技术能力为支撑。",
    },
    education: [
      {
        id: "waterloo",
        school: "滑铁卢大学",
        start: "2025-09",
        end: "2026-12",
        period: "2025年9月—2026年12月",
        degree: "电气与计算机工程硕士",
        detail: "软件工程方向",
      },
      {
        id: "yanshan",
        school: "燕山大学",
        start: "2021-09",
        end: "2025-06",
        period: "2021年9月—2025年6月",
        degree: "电子科学与技术学士",
        detail: "GPA：86 / 100",
      },
    ],
    skills: [
      {
        id: "languages",
        label: "编程语言",
        items: ["Java", "TypeScript", "JavaScript", "Python", "C / C++", "SQL"],
      },
      {
        id: "frontend-mobile",
        label: "前端与移动端",
        items: ["React", "React Native", "Flutter"],
      },
      {
        id: "backend-cloud",
        label: "后端与云服务",
        items: [
          "Spring Boot",
          "Node.js / Express",
          "Django",
          "REST APIs",
          "Microsoft Azure",
          "Google Cloud",
          "Docker",
        ],
      },
      {
        id: "data-ai",
        label: "数据与 AI",
        items: [
          "PostgreSQL",
          "MySQL",
          "MongoDB",
          "Redis",
          "Qwen / Gemini",
          "Stable Diffusion 1.5",
        ],
      },
      {
        id: "project-toolkit",
        label: "其他项目工具",
        items: ["Kotlin", "HTML / CSS", "Git", "Linux", "Bash", "Qt", "CUDA", "TensorFlow / YAMNet"],
      },
    ],
    spokenLanguages: [
      { id: "english", language: "英语", level: "流利" },
      { id: "chinese", language: "中文", level: "母语" },
      { id: "french", language: "法语", level: "基础" },
    ],
    contact: {
      ...sharedContact,
      title: "一起做出经得住检验的产品。",
      intro: "如需沟通全栈、AI 产品或系统工程方向的合作，邮件是最快的联系方式。",
      links: [
        {
          id: "email",
          label: "邮箱",
          value: sharedContact.email,
          href: sharedContact.emailHref,
        },
        {
          id: "phone",
          label: "电话",
          value: sharedContact.phone,
          href: sharedContact.phoneHref,
        },
        {
          id: "website",
          label: "网站",
          value: sharedContact.website,
          href: sharedContact.websiteHref,
          external: true,
        },
        {
          id: "github",
          label: "GitHub",
          value: sharedContact.github,
          href: sharedContact.githubHref,
          external: true,
        },
        {
          id: "resume",
          label: "简历",
          value: "查看 PDF",
          href: sharedContact.resumeHref,
          external: true,
        },
      ],
    },
  },
};

export const getContent = (locale = defaultLocale) => {
  const normalizedLocale = locale.toLowerCase().split("-")[0];
  return content[supportedLocales.includes(normalizedLocale) ? normalizedLocale : defaultLocale];
};

export default content;
