const sharedContact = {
  email: "wangxiwei2002@gmail.com",
  emailHref: "mailto:wangxiwei2002@gmail.com",
  phone: "+1 (437) 872-3279",
  phoneHref: "tel:+14378723279",
  website: "wxw2002a.github.io",
  websiteHref: "https://wxw2002a.github.io/",
  github: "@wxw2002a",
  githubHref: "https://github.com/wxw2002a",
};

const ipmdVideos = [1, 2, 3].map((number) => ({
  src: `/assets/ipmd/video${number}.mp4`,
  poster: `/assets/ipmd/video${number}-poster.jpg`,
  title: `video${number}`,
}));

export const supportedLocales = ["en", "zh"];
export const defaultLocale = "en";

export const content = {
  en: {
    locale: "en",
    localeName: "English",
    meta: {
      title: "Xiwei Wang — Software Engineer",
      description:
        "Xiwei Wang builds full-stack products, AI platforms, mobile applications, backend services, and real-time computer-vision systems.",
    },
    ui: {
      skipToContent: "Skip to main content",
      brandRole: "Engineer / Builder",
      nav: [
        { id: "profile", href: "#profile", label: "Profile" },
        { id: "experience", href: "#experience", label: "Experience" },
        { id: "work", href: "#work", label: "Selected work" },
        { id: "background", href: "#background", label: "Background" },
        { id: "contact", href: "#contact", label: "Contact" },
      ],
      controls: {
        openMenu: "Open menu",
        closeMenu: "Close menu",
        switchLanguage: "切换至中文",
        switchTheme: "Switch color theme",
        lightTheme: "Use light theme",
        darkTheme: "Use dark theme",
      },
      actions: {
        explore: "Explore my work",
        viewDetails: "View role details",
        hideDetails: "Hide role details",
        startConversation: "Start a conversation",
        backToTop: "Back to top",
        scroll: "Scroll to explore",
      },
      projectFilters: [
        { id: "all", label: "All" },
        { id: "systems", label: "Systems" },
        { id: "ai", label: "AI / ML" },
        { id: "gpu", label: "GPU" },
      ],
      sectionLabels: {
        profile: "01 / PROFILE",
        experience: "02 / EXPERIENCE",
        work: "03 / SELECTED WORK",
        background: "04 / BACKGROUND",
        contact: "05 / CONTACT",
      },
      labels: {
        selectedImpact: "Selected impact",
        education: "Education",
        technicalToolkit: "Technical toolkit",
        spokenLanguages: "Spoken languages",
        email: "Email",
        phone: "Phone",
        website: "Website",
        github: "GitHub",
      },
      footerNote: "Designed and engineered with intention.",
    },
    hero: {
      eyebrow: "FULL-STACK / AI PRODUCT / REAL-TIME SYSTEMS",
      name: "XIWEI WANG",
      headlineLead: "I build software",
      headlineAccent: "from end to end.",
      headline: "Full-stack products. AI platforms. Real-time systems.",
      lede: "Software engineer based in Ontario, Canada. I build AI platforms, connected applications, and real-time systems from interface to infrastructure.",
      study:
        "University of Waterloo · MEng, Electrical & Computer Engineering (Software Engineering) · Expected Dec 2026",
    },
    impact: [
      {
        id: "workstreams",
        value: "6",
        label: "cross-functional workstreams",
        detail: "Coordinated across engineering, design, and product",
      },
      {
        id: "response-time",
        value: "−25%",
        label: "average response time",
        detail: "Through multithreaded API and data-access refactoring",
      },
      {
        id: "vision-throughput",
        value: "600",
        label: "images per second, peak",
        detail: "Real-time teacup defect detection in C++ / Qt",
      },
    ],
    capabilities: {
      title: "Product thinking. Engineering depth.",
      intro:
        "I am an Electrical and Computer Engineering MEng candidate at the University of Waterloo. My work spans cross-platform applications, concurrent backend services, AI pipelines, cloud deployment, and real-time industrial software.",
      items: [
        {
          id: "product-delivery",
          index: "01",
          title: "Product delivery",
          text: "Align implementation priorities across engineering, design, and product, and streamline CI/CD and containerized deployment to deliver working software.",
          tags: ["Coordination", "CI/CD", "Delivery"],
        },
        {
          id: "full-stack-products",
          index: "02",
          title: "Full-stack products",
          text: "Build mobile and web experiences with React, React Native, and Flutter, backed by Java/Spring Boot, Node.js/Express, Django, and structured data systems.",
          tags: ["Web", "Mobile", "Backend"],
        },
        {
          id: "ai-real-time",
          index: "03",
          title: "AI & real-time systems",
          text: "Connect LLM and image-generation services in the cloud, and engineer performance-sensitive C++/Qt computer-vision applications on Linux.",
          tags: ["AI", "Cloud", "Computer vision"],
        },
      ],
    },
    experienceIntro: {
      title: "Built across disciplines.",
      text: "Five roles across AI products, mobile platforms, backend systems, and industrial automation.",
    },
    experiences: [
      {
        id: "ipmd",
        videos: ipmdVideos,
        company: "IPMD, Inc.",
        role: "Software Engineering Intern",
        start: "2026-05",
        end: "2026-08",
        period: "May 2026 — Aug 2026",
        location: "California, United States · Remote",
        highlight: { value: "6", label: "cross-functional workstreams" },
        metrics: [{ value: "6", label: "cross-functional workstreams" }],
        bullets: [
          "Built and deployed an end-to-end AI image-generation platform on Microsoft Azure, integrating React/TypeScript, Node.js/Express, Qwen/Gemini, and an internal Stable Diffusion 1.5 inference pipeline for multimodal artwork generation.",
          "Containerized the React frontend, Node.js backend, Qwen service, and Stable Diffusion inference service with Docker, enabling reproducible deployment across AI and application services.",
          "Streamlined CI/CD workflows and coordinated six cross-functional workstreams across engineering, design, and product to align implementation priorities and deliver the MVP.",
        ],
        tech: [
          "React",
          "TypeScript",
          "Node.js / Express",
          "Qwen / Gemini",
          "Stable Diffusion 1.5",
          "Docker",
          "Microsoft Azure",
          "CI/CD",
        ],
      },
      {
        id: "folobotics",
        company: "FoloBotics",
        role: "Full-Stack Developer",
        start: "2026-01",
        end: "2026-04",
        period: "Jan 2026 — Apr 2026",
        location: "Ontario, Canada",
        highlight: { value: "−25%", label: "average response time" },
        metrics: [{ value: "25%", label: "lower average response time" }],
        bullets: [
          "Developed scalable Java/Spring Boot backend services and REST APIs for user, task, recommendation, and warehouse workflows consumed by Flutter clients.",
          "Refactored Java/Spring Boot API and data-access layers with a multithreaded architecture, mitigating race conditions and improving thread-safe operations across PostgreSQL and Redis, reducing average response time by 25%.",
        ],
        tech: [
          "Java",
          "Spring Boot",
          "REST APIs",
          "Flutter",
          "PostgreSQL",
          "Redis",
          "Multithreading",
        ],
      },
      {
        id: "selest-security",
        company: "SELEST Security",
        role: "Full-Stack Developer",
        start: "2025-09",
        end: "2025-12",
        period: "Sep 2025 — Dec 2025",
        location: "Ontario, Canada",
        highlight: { value: "5+", label: "booking and shift workflows" },
        metrics: [
          { value: "5+", label: "booking and shift-management workflows" },
        ],
        bullets: [
          "Built and shipped a multi-role React Native application using TypeScript and JavaScript, Node.js/Express, MongoDB, and Google Cloud, supporting production releases to the App Store and Google Play.",
          "Implemented 5+ booking and shift-management workflows through REST API integration, ensuring reliable state synchronization and data consistency across user roles.",
        ],
        tech: [
          "React Native",
          "TypeScript",
          "JavaScript",
          "Node.js / Express",
          "MongoDB",
          "Google Cloud",
          "REST APIs",
        ],
      },
      {
        id: "hit-robotics",
        company:
          "Harbin Institute of Technology Robot Technology Research Institute",
        role: "Industrial Vision Platform Development Intern",
        start: "2025-05",
        end: "2025-08",
        period: "May 2025 — Aug 2025",
        location: "China",
        highlight: { value: "600", label: "images per second, peak" },
        metrics: [{ value: "600", label: "images per second, peak" }],
        bullets: [
          "Built a real-time C++/Qt computer-vision application on Linux for teacup defect detection, processing up to 600 images per second from live camera feeds while optimizing memory management and integrating application modules.",
          "Developed a Python/Django REST backend for detection logging, parameter synchronization, and offline frame analysis, connecting vision outputs to structured application services.",
        ],
        tech: ["C++", "Qt", "Linux", "Python", "Django", "REST APIs"],
      },
      {
        id: "sinopec",
        company: "Sinopec Group",
        role: "Application Intern at the Information Center",
        start: "2024-06",
        end: "2024-12",
        period: "Jun 2024 — Dec 2024",
        location: "China",
        highlight: { value: "5,000+", label: "storage locations visualized" },
        metrics: [
          { value: "5,000+", label: "storage locations" },
          { value: "<80 ms", label: "real-time synchronization latency" },
        ],
        bullets: [
          "Developed a real-time 2D warehouse visualization component using React and Canvas/SVG, rendering 5,000+ storage locations with live status highlighting and heatmap analytics while maintaining smooth UI performance.",
          "Built real-time data synchronization using WebSocket (Socket.io), streaming PDA scan events and AGV position updates to the React dashboard with under 80 ms latency.",
        ],
        tech: [
          "React",
          "Canvas / SVG",
          "WebSocket",
          "Socket.io",
          "Real-time data",
        ],
      },
    ],
    featured: [
      {
        id: "ai-image-platform",
        title: "From prompt to image.",
        eyebrow: "01 / AI IMAGE PLATFORM · IPMD",
        summary:
          "A multimodal artwork platform connecting React, language models, and an internal Stable Diffusion pipeline. Containerized services and CI/CD bring the experience to Azure.",
        metric: { value: "6", label: "cross-functional workstreams" },
        tech: [
          "React",
          "TypeScript",
          "Qwen / Gemini",
          "Stable Diffusion",
          "Docker",
          "Azure",
        ],
        experienceId: "ipmd",
        videos: ipmdVideos,
      },
      {
        id: "warehouse-visualization",
        title: "A warehouse, live.",
        eyebrow: "02 / REAL-TIME VISUALIZATION · SINOPEC",
        summary:
          "A React and Canvas/SVG dashboard for 5,000+ storage locations. Live status, heatmaps, PDA scans, and AGV positions stay synchronized through Socket.io with under 80 ms latency.",
        metric: { value: "5,000+", label: "storage locations" },
        tech: ["React", "Canvas / SVG", "WebSocket", "Socket.io"],
        experienceId: "sinopec",
      },
      {
        id: "industrial-vision",
        title: "Vision at full speed.",
        eyebrow: "03 / INDUSTRIAL VISION · HIT",
        summary:
          "A real-time C++/Qt application for teacup defect detection, with optimized memory management and a Django backend for detection logs, parameter synchronization, and offline frame analysis.",
        metric: { value: "600", label: "images per second, peak" },
        tech: ["C++", "Qt", "Linux", "Python", "Django"],
        experienceId: "hit-robotics",
        video: {
          src: "/assets/hit-detection-demo.mp4",
          poster: "/assets/hit-detection-poster.jpg",
          title: "HIT · Detection demo",
        },
      },
    ],
    projectsIntro: {
      title: "Engineering beyond the happy path.",
      text: "Further experiments in systems performance, GPU computing, and applied AI.",
    },
    projects: [
      {
        id: "java-tcp-server",
        index: "01",
        category: "systems",
        categoryLabel: "SYSTEMS",
        title: "High-Performance Java Server",
        metric: "120 → ~40 ms",
        description:
          "A multithreaded Java TCP server on Ubuntu with socket-level tuning, reducing latency from 120 ms to approximately 40 ms.",
        tech: ["Java", "TCP", "Ubuntu", "Performance"],
      },
      {
        id: "cuda-convolution",
        index: "02",
        category: "gpu",
        categoryLabel: "GPU",
        title: "CUDA Convolution Acceleration",
        metric: "CUDA 12.4 · RTX 3070",
        description:
          "Implemented 2D convolution CUDA kernels on an RTX 3070 and built Python benchmarks for performance evaluation.",
        tech: ["CUDA 12.4", "C / C++", "Python", "RTX 3070"],
      },
      {
        id: "audio-anomaly-detection",
        index: "03",
        category: "ai",
        categoryLabel: "AI / ML",
        title: "Audio Anomaly Detection",
        metric: "YAMNet",
        description:
          "YAMNet-based classification with thresholding designed to reduce false positives in industrial environments.",
        tech: ["Python", "TensorFlow", "YAMNet", "Audio ML"],
      },
      {
        id: "template-roi-toolkit",
        index: "04",
        category: "systems",
        categoryLabel: "VISION UI",
        title: "Template / ROI Toolkit",
        metric: "Template / ROI",
        description:
          "Proportional template fitting and ROI parameter controls for distortion-free industrial inspection interfaces.",
        tech: ["C / C++", "Qt", "Computer Vision", "UI Systems"],
      },
    ],
    backgroundIntro: {
      title: "Education meets engineering practice.",
      text: "Graduate software engineering study backed by an electronic-systems foundation and a practical full-stack toolkit.",
    },
    education: [
      {
        id: "waterloo",
        school: "University of Waterloo",
        start: "2025-09",
        end: "2026-12",
        period: "Sep 2025 — Dec 2026 (Expected)",
        degree: "Master of Engineering in Electrical and Computer Engineering",
        detail: "Software Engineering",
      },
      {
        id: "yanshan",
        school: "Yanshan University",
        start: "2021-09",
        end: "2025-06",
        period: "Sep 2021 — Jun 2025",
        degree: "Bachelor of Electronic Science and Technology",
        detail: "GPA: 86 / 100",
      },
    ],
    skills: [
      {
        id: "languages",
        label: "Languages",
        items: [
          "Java",
          "TypeScript",
          "JavaScript",
          "Python",
          "C / C++",
          "SQL",
          "HTML / CSS",
        ],
      },
      {
        id: "frontend-mobile",
        label: "Frontend & Mobile",
        items: ["React", "React Native", "Flutter"],
      },
      {
        id: "backend-cloud",
        label: "Backend & Cloud",
        items: [
          "Spring Boot",
          "Node.js / Express",
          "Django",
          "REST APIs",
          "Microsoft Azure",
          "Google Cloud",
          "Docker",
          "CI/CD",
        ],
      },
      {
        id: "data-ai",
        label: "Data & AI",
        items: [
          "PyTorch",
          "PostgreSQL",
          "MySQL",
          "MongoDB",
          "Redis",
          "Qwen / Gemini",
          "Stable Diffusion",
        ],
      },
      {
        id: "project-toolkit",
        label: "Additional project tools",
        items: [
          "Kotlin",
          "Git",
          "Linux",
          "Bash",
          "Qt",
          "CUDA",
          "TensorFlow / YAMNet",
        ],
      },
    ],
    spokenLanguages: [
      { id: "english", language: "English", level: "Fluent" },
      { id: "chinese", language: "Chinese", level: "Native" },
      { id: "french", language: "French", level: "Basic" },
    ],
    contact: {
      ...sharedContact,
      title: "Let’s build something that holds up.",
      intro:
        "For full-stack, AI-enabled product, or systems work, email is the fastest way to reach me.",
      links: [
        {
          id: "email",
          label: "Email",
          value: sharedContact.email,
          href: sharedContact.emailHref,
        },
        {
          id: "phone",
          label: "Phone",
          value: sharedContact.phone,
          href: sharedContact.phoneHref,
        },
        {
          id: "website",
          label: "Website",
          value: sharedContact.website,
          href: sharedContact.websiteHref,
          external: true,
        },
        {
          id: "github",
          label: "GitHub",
          value: sharedContact.github,
          href: sharedContact.githubHref,
          external: true,
        },
      ],
    },
  },

  zh: {
    locale: "zh-CN",
    localeName: "中文",
    meta: {
      title: "Xiwei Wang — 软件工程师",
      description:
        "Xiwei Wang 专注于全栈产品、AI 平台、移动应用、后端服务与实时计算机视觉系统。",
    },
    ui: {
      skipToContent: "跳到主要内容",
      brandRole: "工程师 / 创造者",
      nav: [
        { id: "profile", href: "#profile", label: "简介" },
        { id: "experience", href: "#experience", label: "经历" },
        { id: "work", href: "#work", label: "项目" },
        { id: "background", href: "#background", label: "背景" },
        { id: "contact", href: "#contact", label: "联系" },
      ],
      controls: {
        openMenu: "打开菜单",
        closeMenu: "关闭菜单",
        switchLanguage: "Switch to English",
        switchTheme: "切换配色主题",
        lightTheme: "使用浅色主题",
        darkTheme: "使用深色主题",
      },
      actions: {
        explore: "查看我的经历",
        viewDetails: "查看职位详情",
        hideDetails: "收起职位详情",
        startConversation: "发起联系",
        backToTop: "返回顶部",
        scroll: "向下探索",
      },
      projectFilters: [
        { id: "all", label: "全部" },
        { id: "systems", label: "系统" },
        { id: "ai", label: "AI / 机器学习" },
        { id: "gpu", label: "GPU" },
      ],
      sectionLabels: {
        profile: "01 / 简介",
        experience: "02 / 经历",
        work: "03 / 精选项目",
        background: "04 / 背景",
        contact: "05 / 联系",
      },
      labels: {
        selectedImpact: "代表性成果",
        education: "教育经历",
        technicalToolkit: "技术栈",
        spokenLanguages: "语言能力",
        email: "邮箱",
        phone: "电话",
        website: "网站",
        github: "GitHub",
      },
      footerNote: "用心设计，也用心实现。",
    },
    hero: {
      eyebrow: "全栈 / AI 产品 / 实时系统",
      name: "XIWEI WANG",
      headlineLead: "从界面到系统，",
      headlineAccent: "让软件落地。",
      headline: "全栈产品。AI 平台。实时系统。",
      lede: "现居加拿大安大略省的软件工程师。从用户界面到基础设施，我构建 AI 平台、互联应用与实时系统。",
      study:
        "滑铁卢大学 · 电气与计算机工程硕士（软件工程方向）· 预计 2026 年 12 月毕业",
    },
    impact: [
      {
        id: "workstreams",
        value: "6",
        label: "个跨职能工作流",
        detail: "协调工程、设计与产品团队共同推进",
      },
      {
        id: "response-time",
        value: "−25%",
        label: "平均响应时间",
        detail: "通过多线程 API 与数据访问层重构实现",
      },
      {
        id: "vision-throughput",
        value: "600",
        label: "张图像 / 秒，峰值",
        detail: "以 C++ / Qt 实时检测茶杯缺陷",
      },
    ],
    capabilities: {
      title: "产品思维，工程深度。",
      intro:
        "我正在滑铁卢大学攻读电气与计算机工程硕士。我的工作覆盖跨平台应用、并发后端服务、AI 流程、云端部署与工业实时软件。",
      items: [
        {
          id: "product-delivery",
          index: "01",
          title: "产品交付",
          text: "协调工程、设计与产品团队的实现优先级，优化 CI/CD 流程与容器化部署，推动软件完成交付。",
          tags: ["协作", "CI/CD", "交付"],
        },
        {
          id: "full-stack-products",
          index: "02",
          title: "全栈产品",
          text: "使用 React、React Native 与 Flutter 构建 Web 和移动端体验，并以 Java/Spring Boot、Node.js/Express、Django 与结构化数据系统提供后端支持。",
          tags: ["Web", "移动端", "后端"],
        },
        {
          id: "ai-real-time",
          index: "03",
          title: "AI 与实时系统",
          text: "在云端连接大语言模型与图像生成服务，并在 Linux 上开发对性能敏感的 C++/Qt 计算机视觉应用。",
          tags: ["AI", "云服务", "计算机视觉"],
        },
      ],
    },
    experienceIntro: {
      title: "跨领域的工程实践。",
      text: "五段经历，覆盖 AI 产品、移动平台、后端系统与工业自动化。",
    },
    experiences: [
      {
        id: "ipmd",
        videos: ipmdVideos,
        company: "IPMD, Inc.",
        role: "软件工程实习生",
        start: "2026-05",
        end: "2026-08",
        period: "2026年5月—8月",
        location: "美国加利福尼亚州 · 远程",
        highlight: { value: "6", label: "个跨职能工作流" },
        metrics: [{ value: "6", label: "个跨职能工作流" }],
        bullets: [
          "在 Microsoft Azure 上构建并部署端到端 AI 图像生成平台，集成 React/TypeScript、Node.js/Express、Qwen/Gemini 与内部 Stable Diffusion 1.5 推理流程，支持多模态艺术作品生成。",
          "使用 Docker 将 React 前端、Node.js 后端、Qwen 服务与 Stable Diffusion 推理服务容器化，实现多个 AI 与应用服务的可复现部署。",
          "优化 CI/CD 流程，协调工程、设计与产品团队的 6 个跨职能工作流，对齐实现优先级并完成 MVP 交付。",
        ],
        tech: [
          "React",
          "TypeScript",
          "Node.js / Express",
          "Qwen / Gemini",
          "Stable Diffusion 1.5",
          "Docker",
          "Microsoft Azure",
          "CI/CD",
        ],
      },
      {
        id: "folobotics",
        company: "FoloBotics",
        role: "全栈开发工程师",
        start: "2026-01",
        end: "2026-04",
        period: "2026年1月—4月",
        location: "加拿大安大略省",
        highlight: { value: "−25%", label: "平均响应时间" },
        metrics: [{ value: "25%", label: "平均响应时间降低" }],
        bullets: [
          "开发可扩展的 Java/Spring Boot 后端服务与 REST API，为 Flutter 客户端的用户、任务、推荐与仓库工作流提供支持。",
          "以多线程架构重构 Java/Spring Boot API 与数据访问层，缓解竞态条件，提升 PostgreSQL 与 Redis 操作的线程安全性，使平均响应时间降低 25%。",
        ],
        tech: [
          "Java",
          "Spring Boot",
          "REST APIs",
          "Flutter",
          "PostgreSQL",
          "Redis",
          "多线程",
        ],
      },
      {
        id: "selest-security",
        company: "SELEST Security",
        role: "全栈开发工程师",
        start: "2025-09",
        end: "2025-12",
        period: "2025年9月—12月",
        location: "加拿大安大略省",
        highlight: { value: "5+", label: "个预约与排班工作流" },
        metrics: [{ value: "5+", label: "个预约与排班管理工作流" }],
        bullets: [
          "使用 React Native、TypeScript、JavaScript、Node.js/Express、MongoDB 与 Google Cloud 构建并发布多角色应用，支持 App Store 与 Google Play 的生产版本发布。",
          "通过 REST API 集成实现 5+ 个预约与排班管理工作流，确保不同用户角色之间的状态同步与数据一致性。",
        ],
        tech: [
          "React Native",
          "TypeScript",
          "JavaScript",
          "Node.js / Express",
          "MongoDB",
          "Google Cloud",
          "REST APIs",
        ],
      },
      {
        id: "hit-robotics",
        company: "哈尔滨工业大学机器人技术研究所",
        role: "工业视觉平台开发实习生",
        start: "2025-05",
        end: "2025-08",
        period: "2025年5月—8月",
        location: "中国",
        highlight: { value: "600", label: "张图像 / 秒，峰值" },
        metrics: [{ value: "600", label: "每秒处理图像数，峰值" }],
        bullets: [
          "在 Linux 上构建用于茶杯缺陷检测的实时 C++/Qt 计算机视觉应用，可从相机实时画面中每秒处理多达 600 张图像，并优化内存管理、集成应用模块。",
          "开发 Python/Django REST 后端，用于检测日志、参数同步与离线帧分析，将视觉输出连接至结构化应用服务。",
        ],
        tech: ["C++", "Qt", "Linux", "Python", "Django", "REST APIs"],
      },
      {
        id: "sinopec",
        company: "中国石化集团",
        role: "信息中心应用实习生",
        start: "2024-06",
        end: "2024-12",
        period: "2024年6月—12月",
        location: "中国",
        highlight: { value: "5,000+", label: "个仓储库位可视化" },
        metrics: [
          { value: "5,000+", label: "个仓储库位" },
          { value: "<80 ms", label: "实时同步延迟" },
        ],
        bullets: [
          "使用 React 与 Canvas/SVG 开发实时二维仓储可视化组件，渲染 5,000+ 个库位，提供实时状态高亮与热力图分析，并保持流畅的界面性能。",
          "使用 WebSocket（Socket.io）实现实时数据同步，将 PDA 扫描事件与 AGV 位置更新传输至 React 看板，延迟低于 80 ms。",
        ],
        tech: ["React", "Canvas / SVG", "WebSocket", "Socket.io", "实时数据"],
      },
    ],
    featured: [
      {
        id: "ai-image-platform",
        title: "从提示词，到图像。",
        eyebrow: "01 / AI 图像平台 · IPMD",
        summary:
          "连接 React、大语言模型与内部 Stable Diffusion 推理流程的多模态创作平台，通过容器化服务与 CI/CD 部署至 Azure。",
        metric: { value: "6", label: "个跨职能工作流" },
        tech: [
          "React",
          "TypeScript",
          "Qwen / Gemini",
          "Stable Diffusion",
          "Docker",
          "Azure",
        ],
        experienceId: "ipmd",
        videos: ipmdVideos,
      },
      {
        id: "warehouse-visualization",
        title: "让仓储，实时可见。",
        eyebrow: "02 / 实时可视化 · 中国石化",
        summary:
          "基于 React 与 Canvas/SVG 的仓储看板，呈现 5,000+ 个库位。实时状态、热力图、PDA 扫描与 AGV 位置通过 Socket.io 同步，延迟低于 80 ms。",
        metric: { value: "5,000+", label: "个仓储库位" },
        tech: ["React", "Canvas / SVG", "WebSocket", "Socket.io"],
        experienceId: "sinopec",
      },
      {
        id: "industrial-vision",
        title: "高速视觉，捕捉缺陷。",
        eyebrow: "03 / 工业视觉 · 哈工大",
        summary:
          "面向茶杯缺陷检测的实时 C++/Qt 应用，通过优化内存管理提升处理效率，并以 Django 后端支持检测日志、参数同步与离线帧分析。",
        metric: { value: "600", label: "张图像 / 秒，峰值" },
        tech: ["C++", "Qt", "Linux", "Python", "Django"],
        experienceId: "hit-robotics",
        video: {
          src: "/assets/hit-detection-demo.mp4",
          poster: "/assets/hit-detection-poster.jpg",
          title: "HIT · 检测演示",
        },
      },
    ],
    projectsIntro: {
      title: "面向真实约束的工程实践。",
      text: "继续探索系统性能、GPU 计算与应用 AI。",
    },
    projects: [
      {
        id: "java-tcp-server",
        index: "01",
        category: "systems",
        categoryLabel: "系统",
        title: "高性能 Java 服务器",
        metric: "120 → ~40 ms",
        description:
          "在 Ubuntu 上构建多线程 Java TCP 服务器，通过套接字层调优将延迟从 120 ms 降至约 40 ms。",
        tech: ["Java", "TCP", "Ubuntu", "性能优化"],
      },
      {
        id: "cuda-convolution",
        index: "02",
        category: "gpu",
        categoryLabel: "GPU",
        title: "CUDA 卷积加速",
        metric: "CUDA 12.4 · RTX 3070",
        description:
          "在 RTX 3070 上实现二维卷积 CUDA 内核，并编写 Python 基准测试进行性能评估。",
        tech: ["CUDA 12.4", "C / C++", "Python", "RTX 3070"],
      },
      {
        id: "audio-anomaly-detection",
        index: "03",
        category: "ai",
        categoryLabel: "AI / 机器学习",
        title: "音频异常检测",
        metric: "YAMNet",
        description:
          "基于 YAMNet 的分类方案，结合阈值机制，以减少工业环境中的误报。",
        tech: ["Python", "TensorFlow", "YAMNet", "音频机器学习"],
      },
      {
        id: "template-roi-toolkit",
        index: "04",
        category: "systems",
        categoryLabel: "视觉界面",
        title: "Template / ROI 工具集",
        metric: "Template / ROI",
        description:
          "为工业检测界面实现按比例模板适配与 ROI 参数控制，避免画面变形。",
        tech: ["C / C++", "Qt", "计算机视觉", "界面系统"],
      },
    ],
    backgroundIntro: {
      title: "教育背景与工程实践并行。",
      text: "软件工程研究生学习，以电子系统基础与实用全栈技术能力为支撑。",
    },
    education: [
      {
        id: "waterloo",
        school: "滑铁卢大学",
        start: "2025-09",
        end: "2026-12",
        period: "2025年9月—2026年12月（预计）",
        degree: "电气与计算机工程硕士",
        detail: "软件工程方向",
      },
      {
        id: "yanshan",
        school: "燕山大学",
        start: "2021-09",
        end: "2025-06",
        period: "2021年9月—2025年6月",
        degree: "电子科学与技术学士",
        detail: "GPA：86 / 100",
      },
    ],
    skills: [
      {
        id: "languages",
        label: "编程语言",
        items: [
          "Java",
          "TypeScript",
          "JavaScript",
          "Python",
          "C / C++",
          "SQL",
          "HTML / CSS",
        ],
      },
      {
        id: "frontend-mobile",
        label: "前端与移动端",
        items: ["React", "React Native", "Flutter"],
      },
      {
        id: "backend-cloud",
        label: "后端与云服务",
        items: [
          "Spring Boot",
          "Node.js / Express",
          "Django",
          "REST APIs",
          "Microsoft Azure",
          "Google Cloud",
          "Docker",
          "CI/CD",
        ],
      },
      {
        id: "data-ai",
        label: "数据与 AI",
        items: [
          "PyTorch",
          "PostgreSQL",
          "MySQL",
          "MongoDB",
          "Redis",
          "Qwen / Gemini",
          "Stable Diffusion",
        ],
      },
      {
        id: "project-toolkit",
        label: "其他项目工具",
        items: [
          "Kotlin",
          "Git",
          "Linux",
          "Bash",
          "Qt",
          "CUDA",
          "TensorFlow / YAMNet",
        ],
      },
    ],
    spokenLanguages: [
      { id: "english", language: "英语", level: "流利" },
      { id: "chinese", language: "中文", level: "母语" },
      { id: "french", language: "法语", level: "基础" },
    ],
    contact: {
      ...sharedContact,
      title: "一起做出经得住检验的产品。",
      intro:
        "如需沟通全栈、AI 产品或系统工程方向的合作，邮件是最快的联系方式。",
      links: [
        {
          id: "email",
          label: "邮箱",
          value: sharedContact.email,
          href: sharedContact.emailHref,
        },
        {
          id: "phone",
          label: "电话",
          value: sharedContact.phone,
          href: sharedContact.phoneHref,
        },
        {
          id: "website",
          label: "网站",
          value: sharedContact.website,
          href: sharedContact.websiteHref,
          external: true,
        },
        {
          id: "github",
          label: "GitHub",
          value: sharedContact.github,
          href: sharedContact.githubHref,
          external: true,
        },
      ],
    },
  },
};

export const getContent = (locale = defaultLocale) => {
  const normalizedLocale = locale.toLowerCase().split("-")[0];
  return content[
    supportedLocales.includes(normalizedLocale)
      ? normalizedLocale
      : defaultLocale
  ];
};

export default content;
